# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50efc8ea598c009bbcc3e17ac91dbea84fb30eb992e89a61b082c29b7cdab3138457fa25b31fa84140ad57a7d5c0b5e9b614ba115f52056a8709865bca1b059d

test:
  secret_key_base: e73aeb19b93324ba27a619b63a913d05b6da90117920b392aef25d171b5bd8c22ae091266df157f3c14347c218ac2a870d13710ad847b6f56c5290911d10708b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
